#!/usr/bin/env python

import re,fileinput,stderr,argv

def changegrade(data,first_string number)





for line in data;
	m=re.search(first_string,line)
	if m:
		print re.sub('[%s]'%string.digits,number,line)

	return data;

if__name__='__main__':
	from sys import stdin,stdout,stderr argv
	
	
	(data)=changegrade(stdin, argv[1], argv [2])
		
	 
	
